name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'master'

permissions:
  pages: write
  id-token: write
  actions: read
  contents: read

jobs:
  build_site:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          cache: npm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          BASE_PATH: '/BlogSvelte-Supabase'
        run: pnpm run build

      - name: Debug Environment
        run: |
          echo "Build directory contents:"
          ls -la build/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      actions: read
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
